///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String azkarMassa = 'assets/jsons/azkar_massa.json';
  static const String azkarSabah = 'assets/jsons/azkar_sabah.json';
  static const String azkarSleep = 'assets/jsons/azkar_sleep.json';
  static const String azkarPostPrayer = 'assets/jsons/azkar_post_prayer.json';
  static const String traditionalArabic = 'assets/fonts/Traditional-Arabic.ttf';

}
